DROP TABLE `auditLogs`;--> statement-breakpoint
DROP TABLE `blindConferenceAdjustments`;--> statement-breakpoint
DROP TABLE `blindConferenceSessions`;--> statement-breakpoint
DROP TABLE `contracts`;--> statement-breakpoint
DROP TABLE `divergenceApprovals`;--> statement-breakpoint
DROP TABLE `inventory`;--> statement-breakpoint
DROP TABLE `inventoryCountItems`;--> statement-breakpoint
DROP TABLE `inventoryCounts`;--> statement-breakpoint
DROP TABLE `inventoryMovements`;--> statement-breakpoint
DROP TABLE `labelAssociations`;--> statement-breakpoint
DROP TABLE `labelPrintHistory`;--> statement-breakpoint
DROP TABLE `labelReadings`;--> statement-breakpoint
DROP TABLE `permissions`;--> statement-breakpoint
DROP TABLE `pickingAuditLogs`;--> statement-breakpoint
DROP TABLE `pickingOrderItems`;--> statement-breakpoint
DROP TABLE `pickingOrders`;--> statement-breakpoint
DROP TABLE `pickingReservations`;--> statement-breakpoint
DROP TABLE `pickingWaveItems`;--> statement-breakpoint
DROP TABLE `pickingWaves`;--> statement-breakpoint
DROP TABLE `productBarcodes`;--> statement-breakpoint
DROP TABLE `productLocationMapping`;--> statement-breakpoint
DROP TABLE `products`;--> statement-breakpoint
DROP TABLE `recalls`;--> statement-breakpoint
DROP TABLE `receivingConferences`;--> statement-breakpoint
DROP TABLE `receivingDivergences`;--> statement-breakpoint
DROP TABLE `receivingOrderItems`;--> statement-breakpoint
DROP TABLE `receivingOrders`;--> statement-breakpoint
DROP TABLE `receivingPreallocations`;--> statement-breakpoint
DROP TABLE `returns`;--> statement-breakpoint
DROP TABLE `rolePermissions`;--> statement-breakpoint
DROP TABLE `roles`;--> statement-breakpoint
DROP TABLE `shipments`;--> statement-breakpoint
DROP TABLE `systemUsers`;--> statement-breakpoint
DROP TABLE `tenants`;--> statement-breakpoint
DROP TABLE `userPermissions`;--> statement-breakpoint
DROP TABLE `userRoles`;--> statement-breakpoint
DROP TABLE `warehouseLocations`;--> statement-breakpoint
DROP TABLE `warehouseZones`;--> statement-breakpoint
DROP TABLE `warehouses`;--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin') NOT NULL DEFAULT 'user';--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `tenantId`;